version: '3.5'

services:
  nest-server:
    env_file:
      - .env
    container_name: nest-server
    image: nest-server/nest
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ./:/app
    ports:
      - $PORT:$PORT
    depends_on:
      - nest-mongodb
    restart: always

  nest-mongodb:
    container_name: nest-mongodb
    image: mongo
    volumes:
      - .docker/mongodb:/data/db
    ports:
      - '27017:27017'
    restart: always
